name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Test
      run: cargo test --release --target x86_64-pc-windows-msvc

    - name: Name it d3d9.dll
      run: mv target/x86_64-pc-windows-msvc/release/arrabbiata.dll target/x86_64-pc-windows-msvc/release/d3d9.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: target/x86_64-pc-windows-msvc/release/d3d9.dll
